model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/home/VEAttack/MiniGPT-4/vicuna-7b"
  ckpt: "/home/VEAttack/MiniGPT-4/prerained_minigpt4_7b.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  cococaption:
    eval_file_path: /home/VEAttack/mPLUG-Owl/mPLUG-Owl2/coco_caption_annotations.json  
    img_path: /home/datasets/coco2014/val2014                                  
    max_new_tokens: 30
    batch_size: 8
  refcoco:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path      
    max_new_tokens: 20
    batch_size: 10
  refcocog:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  refcoco+:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  gqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  okvqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path     
    max_new_tokens: 20
    batch_size: 10
  vizwiz:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  iconvqa:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  vsr:
    eval_file_path: cambridgeltl/vsr_zeroshot 
    img_path: /path/to/eval/image/path    
    max_new_tokens: 20
    batch_size: 10
  hm:
    eval_file_path: /path/to/eval/annotation/path  
    img_path: /path/to/eval/image/path 
    max_new_tokens: 20
    batch_size: 100

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /path/to/save/folder_path

  

  

